namespace: k8s_cluster

name: ansible_k8s

version: 1.0.0

readme: README.md

authors:
  - Akshay B <akshay@hkcoder.tech>

description: >
  The easiest way to bootstrap a self-hosted High Availability Kubernetes
  cluster. A fully automated HA k3s etcd install with kube-vip, MetalLB,
  and more.

license:
  - Apache-2.0

tags:
  - etcd
  - high-availability
  - k8s
  - k3s
  - k3s-cluster
  - kube-vip
  - kubernetes
  - metallb
  - rancher

dependencies:
  ansible.utils: "*"
  ansible.posix: "*"
  community.general: "*"
  kubernetes.core: "*"

repository: https://github.com/Akshay2642005/AnsibleK8s
documentation: https://github.com/Akshay2642005/AnsibleK8s
issues: https://github.com/Akshay2642005/AnsibleK8s/issues

build_ignore: []
